import { useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { toast } from "sonner";
import { TOPIC_PACKS } from "@/data/words";
import { getHistory, getWordStats, isMastered, getMissed, getPracticeDays } from "@/lib/storage";
import { useApp } from "@/context/AppContext";
import { calendarDays, wordObject, wordSearch, progressCsv, sessionsCsv, sentencesCsv, downloadText, localDay } from "@/lib/learningTools";
import { practiceStreak } from "@/lib/progressArchive";
import PersonalPacks from "@/components/PersonalPacks";
import { scrambleWord } from "@/lib/arcadeChallenges";
import { downloadOfflinePack } from "@/lib/offlinePack";

export default function LearningTools() {
  const { settings, updateSettings, refresh } = useApp();
  const [tab, setTab] = useState("plan");
  const personal = settings.personalPacks || [];
  const [selected, setSelected] = useState(TOPIC_PACKS[0].id), [worksheet, setWorksheet] = useState("test");
  const [sentence, setSentence] = useState(""), [sentenceIndex, setSentenceIndex] = useState(0), [showKey, setShowKey] = useState(false);
  const packs = [...TOPIC_PACKS, ...personal.map(p => ({ ...p, words: p.words.map(wordObject) }))];
  const pack = packs.find(p => p.id === selected) || packs[0];
  const stats = useMemo(() => getWordStats(), []), history = useMemo(() => getHistory(), []);
  const days = useMemo(() => calendarDays(), []), active = days.slice(-7).filter(d => d.practiced).length;
  const missed = useMemo(() => getMissed().slice(0, 5), []);
  const puzzle = useMemo(() => wordSearch(pack.words), [pack]);
  const current = pack.words[sentenceIndex % pack.words.length];
  const questDone = p => Boolean(settings.questCompletions?.[p.id]) || p.words.filter(w => isMastered(stats[w.word])).length >= 3;
  const weekly = history.filter(h => Date.now() - new Date(h.date).getTime() < 7 * 86400000);
  const correct = weekly.reduce((n, h) => n + (Number(h.correct) || 0), 0), total = weekly.reduce((n, h) => n + (Number(h.correct) || 0) + (Number(h.incorrect) || 0), 0);
  return <div className="space-y-6 learning-tools"><header className="no-print"><h1 className="text-4xl font-black">Your learning workshop</h1><p className="mt-3">Plan, create and explore. Your normal practice contributes to your progress here.</p></header>
    <nav aria-label="Learning tools" className="no-print flex flex-wrap gap-2">{[["plan", "Coach & calendar"], ["quests", "Spelling quests"], ["packs", "Personal packs"], ["print", "Worksheets & offline"], ["sentences", "Sentence builder"]].map(([id, label]) => <button key={id} className="tool-button" aria-pressed={tab === id} onClick={() => setTab(id)}>{label}</button>)}</nav>
    {tab === "plan" && <>
      <section className="tool-card"><h2 className="text-2xl font-bold">Your week</h2><p>{weekly.length} sessions · {total ? Math.round(correct / total * 100) : 0}% accuracy · {active} practice days in the last seven days</p><p>{practiceStreak(getPracticeDays())} day practice streak · Complete a round today to keep it growing.</p><label>Weekly goal <select className="tool-input" value={settings.weeklyGoal || 3} onChange={e => updateSettings({ weeklyGoal: Number(e.target.value) })}>{[1, 2, 3, 4, 5, 6, 7].map(n => <option key={n} value={n}>{n} days</option>)}</select></label><p>{active >= (settings.weeklyGoal || 3) ? "Weekly goal reached!" : `${(settings.weeklyGoal || 3) - active} more practice days to reach your goal.`}</p>
        <div className="my-4 grid grid-cols-7 gap-2">{days.map(d => <div title={`${d.day}: ${d.count ? `${d.count} recent sessions` : d.practiced ? "Practice recorded" : "No practice recorded"}`} className={`rounded-lg p-2 text-center text-xs ${d.practiced ? "bg-emerald-700 text-white" : "bg-slate-800 text-slate-300"}`} key={d.day}>{d.day.slice(8)}<br />{d.practiced ? "✓" : "—"}</div>)}</div><p className="text-sm">The last 28 days; ticks mark completed sessions.</p>
        <button className="tool-button" onClick={() => downloadText("spellbee-word-progress.csv", progressCsv(), "text/csv")}>Export word progress CSV</button><button className="tool-button" onClick={() => downloadText("spellbee-sessions.csv", sessionsCsv(), "text/csv")}>Export recent sessions CSV</button><p className="text-sm">Session exports include your most recent 100 rounds.</p>
      </section>
      <section className="tool-card"><h2 className="text-2xl font-bold">A short practice plan</h2><ol className="my-3 list-decimal space-y-3 pl-5"><li><Link to="/practice?mode=smart&difficulty=adaptive">Start with Smart Practice</Link> to work on your current level.</li><li><Link to="/practice?mode=mistakes&difficulty=mixed">Revisit tricky spellings</Link>{missed.length ? `: ${missed.map(w => w.word).join(", ")}.` : " after you have some mistakes to learn from."}</li><li><Link to="/arcade?game=detective">Try a short Word Detective quiz</Link> to check what has stuck.</li></ol><p>Try these on separate days. The plan adapts to the mistakes recorded in your practice.</p></section>
      <Link className="tool-button" to="/tournament">Enter this week's tournament</Link><Link className="tool-button" to="/arcade">Beat your arcade personal best</Link>
    </>}
    {tab === "quests" && <section className="space-y-4"><h2 className="text-2xl font-bold">The spelling gardens quest</h2><p>Finish a full garden round to unlock the next adventure. You can revisit every unlocked garden. Existing three-word mastery still counts, and completed rounds stay unlocked.</p>{TOPIC_PACKS.map((p, i) => { const count = p.words.filter(w => isMastered(stats[w.word])).length; const previous = TOPIC_PACKS[i - 1]; const unlocked = !previous || questDone(previous); return <article key={p.id} className="tool-card"><h3 className="text-xl font-bold">Garden {i + 1}: {p.title}</h3><p>{count} words mastered · {questDone(p) ? "Quest complete" : unlocked ? "Ready to explore" : "Unlock the previous garden first"}</p>{unlocked && <Link className="tool-button" to={`/practice?mode=topic&topic=${p.id}&difficulty=mixed`}>Explore garden</Link>}</article>; })}</section>}
    {tab === "packs" && <PersonalPacks onPrint={id => { setSelected(id); setTab("print"); }} />}
    {(tab === "print" || tab === "sentences") && <label className="no-print block">Choose a pack<select className="tool-input" value={selected} onChange={e => { setSelected(e.target.value); setSentenceIndex(0); setSentence(""); }}>{packs.map(p => <option key={p.id} value={p.id}>{p.title}</option>)}</select></label>}
    {tab === "print" && <><div className="no-print flex flex-wrap gap-2"><select aria-label="Worksheet type" className="tool-input" value={worksheet} onChange={e => setWorksheet(e.target.value)}><option value="test">Spelling test</option><option value="search">Word search</option><option value="scramble">Word scramble</option></select><label><input type="checkbox" checked={showKey} onChange={e => setShowKey(e.target.checked)} /> Include answer key</label><button className="tool-button" onClick={() => window.print()}>Print / save PDF</button><button className="tool-button" onClick={() => downloadOfflinePack(pack.title, pack.words)}>Download offline practice</button><p>Download a self-contained practice file with saved rounds, missed-word replay and CSV results. Open it without internet; speech depends on installed voices. Offline results stay separate from your account.</p></div><section className="worksheet tool-card"><h2 className="text-2xl font-bold">{pack.title} · {worksheet === "test" ? "Spelling test" : worksheet === "scramble" ? "Word scramble" : "Word search"}</h2><p>Name: ____________________ Date: __________</p>{worksheet === "test" ? <ol className="list-decimal space-y-5 p-6">{pack.words.map(w => <li key={w.word}>__________________________________</li>)}</ol> : worksheet === "scramble" ? <ol className="list-decimal space-y-5 p-6">{pack.words.map(w => <li key={w.word}>{scrambleWord(w.word)} → __________________________</li>)}</ol> : <><pre className="my-5 overflow-auto font-mono leading-loose tracking-widest">{puzzle.grid.map(row => row.join(" ")).join("\n")}</pre><p>Find: {puzzle.placements.map(p => p.word).join(", ")}. Words can run across, down, diagonally or backwards.</p></>}{showKey && <div className="answer-key"><h3 className="text-xl font-bold">Answer key · {pack.title}</h3>{worksheet !== "search" ? <ol className="list-decimal pl-6">{pack.words.map(w => <li key={w.word}>{w.word}</li>)}</ol> : puzzle.placements.map(p => <p key={p.word}>{p.word}: row {p.row + 1}, column {p.col + 1}, {p.direction}</p>)}</div>}</section></>}
    {tab === "sentences" && <section className="tool-card space-y-3"><h2 className="text-2xl font-bold">Use “{current.word}” in a sentence</h2><p>{current.definition}</p><label className="block">Your sentence<textarea className="tool-input" value={sentence} maxLength={1000} onChange={e => setSentence(e.target.value)} rows={4} /></label><button className="tool-button" onClick={() => { const tokens = sentence.toLowerCase().match(/[a-z]+(?:['-][a-z]+)*/g) || []; if (!tokens.includes(current.word.toLowerCase()) || tokens.length < 4) { toast.error("Include the word in a sentence of at least four words."); return; } updateSettings({ sentenceJournal: [...(settings.sentenceJournal || []), { word: current.word, sentence: sentence.trim(), date: localDay() }].slice(-100) }); refresh(); toast.success("Saved. Compare your meaning with the example below."); }}>Save sentence</button><details><summary>Compare with an example</summary><p>{current.example || "Read your sentence aloud and check that the word fits its meaning."}</p><p>Saving checks that you used the word; it does not grade grammar or meaning.</p></details><button className="tool-button" onClick={() => { setSentenceIndex(i => i + 1); setSentence(""); }}>Next word</button><button className="tool-button" disabled={!(settings.sentenceJournal || []).length} onClick={() => downloadText("spellbee-sentences.csv", sentencesCsv(settings.sentenceJournal), "text/csv")}>Export sentence journal CSV</button><h3 className="font-bold">Your recent sentences</h3>{(settings.sentenceJournal || []).slice(-5).reverse().map((s, i) => <p key={i}>{s.date} · {s.sentence}</p>)}</section>}
  </div>;
}
